### ISSUE TITLE
sfml 2.6 : Unable to find native library sfml-activity-d

### ISSUE THREAD

**Issue by Nathan-M-code** [4rcz3r/SFML-Android-Template#2]
Hello,
Thank you for this template project,
I am trying to follow your guide with SFML 2.6
Build passed but on execution I have a fatal error :
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.you.example.debug/android.app.NativeActivity}: java.lang.IllegalArgumentException: Unable to find native library sfml-activity-d`
Because I use SFML 2.6, I changed the CMakeLists.txt a bit by the following :
```
cmake_minimum_required(VERSION 3.22)

project(Example)

set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -u ANativeActivity_onCreate")

set(CMAKE_MAP_IMPORTED_CONFIG_RELWITHDEBINFO RELEASE)

set(PATH_TO_SFML ${ANDROID_NDK}/sources/third_party/sfml)

set(SFML_DIR ${PATH_TO_SFML}/lib/${ANDROID_ABI}/cmake/SFML)
message(STATUS ${SFML_DIR})
find_package(SFML 2.6 COMPONENTS system window graphics REQUIRED)

set(PATH_TO_SOURCES src/main/cpp)
add_library(example SHARED
        ${PATH_TO_SOURCES}/main.cpp
        )
        
target_compile_features(example PUBLIC cxx_std_20)

add_library(openal SHARED IMPORTED)
set_target_properties(openal PROPERTIES IMPORTED_LOCATION_RELEASE ${PATH_TO_SFML}/extlibs/lib/${ANDROID_ABI}/libopenal.so)
set_target_properties(openal PROPERTIES IMPORTED_LOCATION_DEBUG ${PATH_TO_SFML}/extlibs/lib/${ANDROID_ABI}/libopenal.so)

target_link_libraries(example
        log
        android
        sfml-system
        sfml-window
        sfml-graphics
        sfml-activity
        -Wl,--whole-archive sfml-main -Wl,--no-whole-archive
        openal
        EGL
        GLESv1_CM
        )
```

Everything on the SFML compilation went good. All .so files are here.
I don't understand why sfml-activity-d is not found, do you have an idea ?

**Comment by 4rcz3r** [comment]
Hi,
I'm just guessing but since that project works fine for me, then maybe there's something wrong with your sfml installation or with your Android Studio configuration.
Are those .so files (libsfml-activity-d.so) packed into your apk?
Have you changed something else?
Could you maybe send me your project and that example apks you made? idk

**Comment by Nathan-M-code** [comment]
Thank you for the quick answer.
Yes libsfml-activity-d.so is packed into the apk :
![image](https://github.com/4rcz3r/SFML-Android-Template/assets/57316092/9488d555-ac4e-4416-af16-0cc705c9f4eb)
Nothing differs from your project environment but sfml version to 2.6 and NDK version to 25.2.9519653
Here is the build.gradle
```
plugins {
    id 'com.android.application'
}

android {
    defaultConfig {
        applicationId "com.you.example"
        versionCode 1
        versionName "1.0"

        externalNativeBuild {
            cmake {
                cppFlags ""
                arguments "-DANDROID_STL=c++_shared"
                abiFilters 'armeabi-v7a'
            }
        }
        targetSdk 33
        minSdk 22
    }

    splits {
        abi {
            enable true
            reset()
            include "armeabi-v7a"
            universalApk true
        }
    }

    buildTypes {
        release {
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
            externalNativeBuild {
                cmake {
                    cppFlags "-O2"
                }
            }
        }
        debug {
            externalNativeBuild {
                cmake {
                    cppFlags ""
                }
            }
            versionNameSuffix "-d"
            applicationIdSuffix '.debug'
        }
    }
    externalNativeBuild {
        cmake {
            path file('CMakeLists.txt')
        }
    }
    buildToolsVersion '33.0.0'
    ndkVersion '25.2.9519653'
    compileSdk 33
    namespace 'com.you.example'
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.5.1'
}
```
I put the project folder in attachments, and the apk. 
[project.zip](https://github.com/4rcz3r/SFML-Android-Template/files/12068480/project.zip)

**Comment by 4rcz3r** [comment]
I will try to check today the project you send.
If nothing changed, if you didn't make changes in sfml source code you have
to link sfml-network too.
Now I can only advise you to make cmakelists.txt as similar to mine as
possible.

**Comment by Nathan-M-code** [comment]
Yeah I tried with same cmakelists as yours (except SFML::Component-> sfml-component) but I've got the same error.
Thank you for helping me.
If I found out something I come back to you.

**Comment by 4rcz3r** [comment]
Okay, I've got some problems using your cmakelists (with audio and network it works, I'll put it below) but I think it's not your problem.
Do you try to run your app in emulator? Because "default" ones use x86 architecture so if you compile only for armeabi-v7a your emulator actually may lack it's libs in apk...?
[CMakeLists.txt](https://github.com/4rcz3r/SFML-Android-Template/files/12070320/CMakeLists.txt)

**Comment by Nathan-M-code** [comment]
I use my own smartphone to test, it is a xiaomi redmi 8. I have already managed to have a sfml 2.5 app working, but I didn't use a cmakelists.txt file but the Application.mk stuff. I would like to use your method with cmake as I am accustomed with cmake.
I didn't try with  armeabi-v8 yet, I'm going to try it out

**Comment by Nathan-M-code** [comment]
It is working on arm64-v8a ! My bad I should have tested that earlier. I am sorry to made you waste your time.

**Comment by 4rcz3r** [comment]
Great, I'm happy that I could help ;)
