### ISSUE TITLE
sf::priv::getActivity(): assertion "states != NULL" failed

### ISSUE THREAD

**Issue by Nathan-M-code** [4rcz3r/SFML-Android-Template#3]
Hey,
I am trying to follow your guide with SFML 2.6
Build passed but on execution I have a fatal error :
```
2023-08-15 12:55:24.780 20653-20653 libEGL                  com.you.example.debug                E  validate_display:89 error 3001 (EGL_NOT_INITIALIZED)
2023-08-15 12:55:24.781 20653-20653 libc                    com.you.example.debug                A  C:\FactoryCapi\external_deps\SFML\src\SFML\System\Android\Activity.cpp:75: sf::priv::ActivityStates &sf::priv::getActivity(): assertion "states != NULL" failed
2023-08-15 12:55:24.781 20653-20653 libc                    com.you.example.debug                A  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 20653 (u.example.debug), pid 20653 (u.example.debug)
```
I am using several libraries with SFML but I already made a simple project to check and it was ok (launched as expected).
But now I'm using my full source of my game and I have this error.
Just want to you if you already dealt with this, or have any idea about where the problem could come from.
The error occurred before the main is executed.
Thank you

**Comment by Nathan-M-code** [comment]
To explain a little bit my cmake stuff and what relies on what:
The example lib finally built relies on a custom lib FactoryCapi_flow
```
target_link_libraries(example PUBLIC
    FactoryCapi_flow
    log
    android
    sfml-graphics
    sfml-audio
    sfml-activity
    sfml-network
    -Wl,--whole-archive sfml-main -Wl,--no-whole-archive
    TGUI::TGUI
    TGUI::Activity
    EnTT::EnTT
    openal
    EGL
    GLESv1_CM
)
```

FactoryCapi_flow relies on FactoryCapi_core
```
target_link_libraries(
  FactoryCapi_flow PUBLIC
  FactoryCapi_core
)
``` 

FactoryCapi_core is built with those lib
```
target_link_libraries(
  FactoryCapi_core PUBLIC
  sfml-graphics
  sfml-system
  absl::flags
  absl::flags_parse
#  gRPC::grpc++_reflection
  gRPC::grpc++
  protobuf::libprotobuf
  quill::quill
)
```

**Comment by 4rcz3r** [comment]
Hi,

> Message ID: ***@***.***>
>
as you said the example project you made worked so since the problem is
somewhere else in your code I can't help much. If you really can't
backtrace it and you know it should work, my only idea is to comment out
all your code and try adding elements one by one.

**Comment by Nathan-M-code** [comment]
One of my custom file was using sf::Shader, unavailable on android with SFML.
Anyway now it's working, thank you
