### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Faser45** [4rcz3r/SFML-Android-Template#4]
Hello, I need help! I've been trying to make the simplest program for Android for almost a month now, but I can't do it. Nothing is shown on my phone screen when I launch the application (I did everything according to the instructions, and my phone is connected to the PC). Reply here if you can help me!

P.S. If you need any information about the program, I am ready to provide it.

**Comment by 4rcz3r** [comment]
Hi, sorry but I won't help someone whose country has invaded innocent Ukraine unless he admits it and the fact that Putin is a war criminal. Then you can tell me something more about what doesn't work and I'll try to help you or look for help somewhere else.

**Comment by Faser45** [comment]
Sorry, but I in no way support what our president is doing. I am for world peace. And the fact about our president that you proved remains a fact

**Comment by 4rcz3r** [comment]
Thank you, now I can help you with a clearer conscience.
Did you change sth in that template? Where exactly is the problem?

**Comment by Faser45** [comment]
I changed a lot of things in the template to accommodate new versions of plugins and Cmake. I changed the main code (I made it like in the basic SFML example, so that the program would simply display a green circle). But I started doing this only after I was convinced that the program did not work with the original template. I have attached the code build.grandle(:app) as well as AndroidManifest.xml

**////////////////////////build.grandle(:app)///////////////////////**

`plugins {
    id 'com.android.application'
}

android {
    defaultConfig {
        applicationId "Joint_for_Android"
        versionCode 1
        versionName "1.0"

        externalNativeBuild {
            cmake {
                cppFlags ""
                arguments "-DANDROID_STL=c++_static"
                abiFilters 'armeabi-v7a', 'x86', "arm64-v8a", "x86_64"
            }
        }
        targetSdk 33
        minSdk 29
    }

    splits {
        abi {
            enable true
            reset()
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
            universalApk true
        }
    }

    buildTypes {
        release {
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
            externalNativeBuild {
                cmake {
                    cppFlags "-O2"
                }
            }
        }
        debug {
            externalNativeBuild {
                cmake {
                    cppFlags ""
                }
            }
            versionNameSuffix "-d"
            applicationIdSuffix '.debug'
        }
    }
    externalNativeBuild {
        cmake {
            version "3.27.5"
            path file('CMakeLists.txt')
        }
    }
    defaultConfig {
        compileSdk 33
    }
    ndkVersion '25.1.8937393'
    namespace 'Joint_for_Android'
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}`

**/////////////////////////AndroidManifest///////////////////////////**

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">
    <uses-permission android:name="com.google.android.gms.permission.AD_ID"/>

    <uses-feature android:required="true" android:glEsVersion="0x00010001" />

    <application
        android:allowBackup="true"
        android:fullBackupContent="true"
        android:icon="@mipmap/ic_launcher"
        android:label="Joint"
        android:roundIcon="@mipmap/ic_launcher_round"
        tools:targetApi="33"
        android:extractNativeLibs="true"
        tools:ignore="DataExtractionRules">

        <activity
            android:name="android.app.NativeActivity"
            android:configChanges="orientation|keyboardHidden|screenSize|screenLayout"
            android:exported="true"
            android:screenOrientation="userLandscape"
            android:extractNativeLibs="true"
            android:theme="@style/AppTheme">


            <meta-data
                android:name="android.app.lib_name"
                android:value="@string/sfml_activity_x" />
            <meta-data
                android:name="sfml.app.lib_name"
                android:value="Joint_for_Android" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>`

**Comment by Faser45** [comment]
I'm guessing the problem is the error that LogCat outputs: "USNET: appName: Joint_for_Android.debug"

**Comment by 4rcz3r** [comment]
It doesn't tell me too much. I think it'd be easier if you'd try to run app from my template not changing anything except necessary version numbers.
Maybe I could send you working app built from that template if the problem would be with your device (?) but I don't really think it'll help and you should test it rather on emulator than your own smartphone...
I could also later see your app if you would send it.
[app-universal-debug.zip](https://github.com/4rcz3r/SFML-Android-Template/files/12844596/app-universal-debug.zip)

**Comment by Faser45** [comment]
I downloaded the same file again and did everything the same as the first time, and it worked! Thank you very much! But I would like to ask you a question. If I still have a question about the port of the SFML game on Android, can I contact you? It’s just that none of my acquaintances and friends know anything about Android development :(

**Comment by 4rcz3r** [comment]
I'm just hobbyist but yes. You can also mail me: 4rcz3r at gmail.com if you
won't like to ask here. And I don't promise anything.
